import { Badge, BlockStack, Button, InlineStack, Select, Text } from "@shopify/polaris";
import { useState } from "react";
import type { MapAwareSeoGap } from "@/lib/seo/analysis";
import type { TopicalMapCommandCenter } from "@/lib/topical-map/command-center";
import { Provenance } from "./MapPagesPanel";
import styles from "../seo-pilot-responsive.module.css";

export function MapWorkPanel({ map, gaps, busy, done, onPropose }: { map: TopicalMapCommandCenter; gaps: MapAwareSeoGap[]; busy: Set<string>; done: Set<string>; onPropose: (gap: MapAwareSeoGap) => void }) {
  const [family, setFamily] = useState("all"), [priority, setPriority] = useState("all"), [state, setState] = useState("all"), [blocker, setBlocker] = useState("all");
  const linkGap = (from: string, to: string) => gaps.find(g => g.kind === "link" && g.fromUrl === from && g.toUrl === to);
  return <div className={styles.commandCenter}><BlockStack gap="500">
    <BlockStack gap="100"><Text as="h2" variant="headingLg">Links &amp; technical</Text><Text as="p" tone="subdued">Act on governed links here. Technical rules remain visible with accurate execution boundaries.</Text></BlockStack>
    <div className={styles.filterGrid}><Select label="Filter by rule family" options={[{label:"All work",value:"all"},{label:"Internal links",value:"links"},{label:"Redirects",value:"redirects"},{label:"Canonicalization",value:"canonical"},{label:"Indexation",value:"indexation"}]} value={family} onChange={setFamily}/><Select label="Filter by priority" options={[{label:"All priorities",value:"all"},{label:"High",value:"high"},{label:"Medium",value:"medium"},{label:"Low",value:"low"}]} value={priority} onChange={setPriority}/><Select label="Filter by state" options={[{label:"All states",value:"all"},{label:"Candidate",value:"candidate"},{label:"Blocked",value:"blocked"}]} value={state} onChange={setState}/><Select label="Filter by blocker" options={[{label:"All blocker states",value:"all"},{label:"Evidence",value:"evidence"},{label:"Review",value:"review"}]} value={blocker} onChange={setBlocker}/></div>
    {(family === "all" || family === "links") && <WorkSection title="Required internal links">{map.work.internalLinks.map(link => { const gap = linkGap(link.fromUrl, link.toUrl); const key = gap?.ruleIds.join("|") ?? link.ruleIds.join("|"); return <section className={styles.listRow} key={`${link.fromUrl}-${link.toUrl}`}><BlockStack gap="200"><Text as="h4" variant="headingSm">{link.fromUrl} → {link.toUrl}</Text><Text as="p">{link.requiredAction ?? "Add required internal link"}</Text><Text as="p" tone="subdued">Anchor: {link.recommendedAnchor ?? "Use map-approved context"} · State: {link.currentBodyState ?? "Unknown"}</Text><InlineStack align="space-between" blockAlign="center" wrap><Provenance ruleIds={link.ruleIds} map={map}/>{done.has(key) ? <Badge tone="success">Proposal created</Badge> : <Button size="slim" variant="primary" disabled={!gap} loading={busy.has(key)} onClick={() => gap && onPropose(gap)}>Create link proposal</Button>}</InlineStack>{!gap && <Text as="p" tone="caution">No actionable analysis candidate exists for this rule.</Text>}</BlockStack></section>; })}</WorkSection>}
    {(family === "all" || family === "redirects") && <WorkSection title="Redirects">{map.work.redirects.map(row => <TechnicalRow key={row.source} title={`${row.source} → ${row.finalTarget}`} detail={row.requiredAction ?? row.knownState ?? "Review redirect"} warning="Redirect execution is not available from SEO Pilot" ruleIds={row.ruleIds} map={map}/>)}</WorkSection>}
    {(family === "all" || family === "canonical") && <WorkSection title="Canonicalization">{map.work.canonicalization.map(row => <TechnicalRow key={row.currentUrl} title={`${row.currentUrl} → ${row.proposedCanonicalUrl}`} detail={row.decision ?? row.evidence ?? "Review canonical"} warning="Canonical and indexation changes require a separately permitted execution path" ruleIds={row.ruleIds} map={map}/>)}</WorkSection>}
    {(family === "all" || family === "indexation") && <WorkSection title="Indexation">{map.work.indexation.map(row => <TechnicalRow key={row.currentUrl} title={row.currentUrl} detail={row.decision ?? row.publishingState ?? "Review indexation"} warning="Canonical and indexation changes require a separately permitted execution path" ruleIds={row.ruleIds} map={map}/>)}</WorkSection>}
    <WorkSection title="Evidence and review blockers">{[...map.blockers.evidence, ...map.blockers.reviews].map(row => <section className={styles.listRow} key={row.ruleIds.join()}><BlockStack gap="200"><Text as="h4" variant="headingSm">{row.name}</Text><Text as="p">{row.text}</Text><Provenance ruleIds={row.ruleIds} map={map}/></BlockStack></section>)}</WorkSection>
  </BlockStack></div>;
}
function WorkSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><BlockStack gap="200"><Text as="h3" variant="headingMd">{title}</Text><div className={styles.compactList}>{children}</div></BlockStack></section>; }
function TechnicalRow({ title, detail, warning, ruleIds, map }: { title: string; detail: string; warning: string; ruleIds: string[]; map: TopicalMapCommandCenter }) { return <section className={styles.listRow}><BlockStack gap="200"><InlineStack align="space-between" wrap><Text as="h4" variant="headingSm">{title}</Text><Badge tone="attention">Live execution prohibited</Badge></InlineStack><Text as="p">{detail}</Text><Text as="p" tone="caution">{warning}</Text><Button size="slim" disabled>Execution blocked</Button><Provenance ruleIds={ruleIds} map={map}/></BlockStack></section>; }
