import { Badge, BlockStack, Button, Checkbox, InlineStack, Select, Text } from "@shopify/polaris";
import { useState } from "react";
import type { MapAwareSeoAnalysis, MapAwareSeoGap } from "@/lib/seo/analysis";
import type { TopicalMapCommandCenter } from "@/lib/topical-map/command-center";
import { topicalMapInternalLinkRequiresAddition } from "@/lib/topical-map/action-eligibility";
import { normalizeTopicalMapPriority } from "@/lib/topical-map/priority";
import { Provenance } from "./MapPagesPanel";
import styles from "../seo-pilot-responsive.module.css";

export function workRowMatchesFilters(row: { priority?: string; state: "candidate" | "advisory" | "blocked"; blocker: "clear" | "evidence" | "review" }, filters: { priority: string; state: string; blocker: string }) { return (filters.priority === "all" || priorityBand(row.priority) === filters.priority) && (filters.state === "all" || row.state === filters.state) && (filters.blocker === "all" || row.blocker === filters.blocker); }
export const priorityBand = normalizeTopicalMapPriority;
export function globalBlockersVisible(filters: { family: string; priority: string; state: string; blocker: string }) { return filters.family === "all" && filters.priority === "all" && filters.state === "all" && filters.blocker !== "clear"; }
type LinkRule = TopicalMapCommandCenter["work"]["internalLinks"][number];
type Suppressed = MapAwareSeoAnalysis["suppressed"][number];
export function internalLinkPresentation(link: LinkRule, gaps: MapAwareSeoGap[], suppressed: Suppressed[]): "candidate" | "managed" | "evidence_unavailable" | "gate_required" | "neutral" {
  const suppression = suppressed.find(item => item.page === link.fromUrl && item.ruleIds.some(ruleId => link.ruleIds.includes(ruleId)));
  if (suppression && ["manual_gate", "activation_blocking", "conditions_unsatisfied"].includes(suppression.reason)) return "gate_required";
  if (gaps.some(gap => gap.kind === "link" && gap.fromUrl === link.fromUrl && gap.toUrl === link.toUrl)) return "candidate";
  if (!topicalMapInternalLinkRequiresAddition(link.requiredAction)) return "neutral";
  if (!/^\/blogs\/[^/]+\/[^/]+$/.test(link.fromUrl)) return "managed";
  const unavailable = suppression?.reason.startsWith("observation_unavailable");
  return unavailable ? "evidence_unavailable" : "neutral";
}

export function MapWorkPanel({ map, gaps, suppressed = [], selected, done, onToggle, onSelectVisible }: { map: TopicalMapCommandCenter; gaps: MapAwareSeoGap[]; suppressed?: Suppressed[]; selected: Set<string>; done: Set<string>; onToggle: (candidateId: string) => void; onSelectVisible: (candidateIds: string[], select: boolean) => void }) {
  const [family, setFamily] = useState("all"), [priority, setPriority] = useState("all"), [state, setState] = useState("all"), [blocker, setBlocker] = useState("all");
  const linkGap = (from: string, to: string) => gaps.find(g => g.kind === "link" && g.fromUrl === from && g.toUrl === to);
  const visible = (rowPriority: string | undefined, rowState: "candidate" | "advisory" | "blocked", rowBlocker: "clear" | "evidence" | "review") => workRowMatchesFilters({ priority: rowPriority, state: rowState, blocker: rowBlocker }, { priority, state, blocker });
  const visibleLinks = map.work.internalLinks.filter(link => { const presentation = internalLinkPresentation(link, gaps, suppressed); return presentation === "candidate" ? visible(link.priority, "candidate", "clear") : presentation === "evidence_unavailable" ? visible(link.priority, "blocked", "evidence") : presentation === "gate_required" ? visible(link.priority, "advisory", "evidence") : (priority === "all" || priorityBand(link.priority) === priority) && state === "all" && blocker === "all"; });
  const visibleRedirects = map.work.redirects.filter(row => (priority === "all" || priorityBand(row.priority) === priority) && state === "all" && blocker === "all");
  const visibleIds = visibleLinks.map(link => linkGap(link.fromUrl, link.toUrl)).filter((gap): gap is MapAwareSeoGap => Boolean(gap && !done.has(gap.candidateId))).map(gap => gap.candidateId);
  return <div className={styles.commandCenter}><BlockStack gap="500">
    <BlockStack gap="100"><Text as="h2" variant="headingLg">Links &amp; technical</Text><Text as="p" tone="subdued">Act on governed links here. Technical rules remain visible with accurate execution boundaries.</Text></BlockStack>
    <div className={styles.filterGrid}><Select label="Filter by rule family" options={[{label:"All work",value:"all"},{label:"Internal links",value:"links"},{label:"Redirects",value:"redirects"},{label:"Canonicalization",value:"canonical"},{label:"Indexation",value:"indexation"}]} value={family} onChange={setFamily}/><Select label="Filter by priority" options={[{label:"All priorities",value:"all"},{label:"High",value:"high"},{label:"Medium",value:"medium"},{label:"Low",value:"low"}]} value={priority} onChange={setPriority}/><Select label="Filter by state" options={[{label:"All states",value:"all"},{label:"Candidate",value:"candidate"},{label:"Advisory",value:"advisory"},{label:"Blocked",value:"blocked"}]} value={state} onChange={setState}/><Select label="Filter by requirement" options={[{label:"All requirements",value:"all"},{label:"Clear",value:"clear"},{label:"Evidence gate",value:"evidence"},{label:"High-stakes review",value:"review"}]} value={blocker} onChange={setBlocker}/></div>
    {(family === "all" || family === "links") && <WorkSection title="Required internal links">{visibleIds.length > 0 && <InlineStack gap="200"><Button size="slim" onClick={() => onSelectVisible(visibleIds, true)}>Select all visible</Button><Button size="slim" variant="plain" onClick={() => onSelectVisible(visibleIds, false)}>Clear visible</Button></InlineStack>}{visibleLinks.map(link => { const gap = linkGap(link.fromUrl, link.toUrl); const presentation = internalLinkPresentation(link, gaps, suppressed); const label = presentation === "candidate" ? "Candidate" : presentation === "managed" ? "Managed in Store Pilot" : presentation === "evidence_unavailable" ? "Evidence unavailable" : presentation === "gate_required" ? "Gate required" : "No action candidate"; return <section className={styles.listRow} key={`${link.fromUrl}-${link.toUrl}`}><BlockStack gap="200"><InlineStack align="space-between" wrap><Text as="h4" variant="headingSm">{link.fromUrl} → {link.toUrl}</Text><Badge tone={presentation === "candidate" ? "success" : presentation === "evidence_unavailable" || presentation === "gate_required" ? "attention" : "info"}>{label}</Badge></InlineStack><Text as="p"><b>Map-recorded state:</b> {link.currentBodyState ?? "Not specified"}</Text><Text as="p"><b>Required action:</b> {link.requiredAction ?? "Not specified"}</Text><Text as="p"><b>Purpose:</b> {link.linkPurpose ?? "Not specified"}</Text><Text as="p"><b>Verification:</b> {link.verification ?? "Not specified"}</Text><Text as="p" tone="subdued">Priority: {link.priority ?? "unspecified"} · Anchor: {link.recommendedAnchor ?? "Use map-approved context"}</Text><InlineStack align="space-between" blockAlign="center" wrap><Provenance ruleIds={link.ruleIds} map={map}/>{gap && done.has(gap.candidateId) ? <Badge tone="success">Proposal created</Badge> : gap ? <Checkbox label="Select for proposal" checked={selected.has(gap.candidateId)} onChange={() => onToggle(gap.candidateId)}/> : null}</InlineStack>{presentation === "managed" ? <Text as="p" tone="subdued">The non-blog source is evaluated through Store Pilot.</Text> : presentation === "evidence_unavailable" ? <Text as="p" tone="caution">Persisted observation evidence is unavailable.</Text> : presentation === "gate_required" ? <Text as="p" tone="caution">Condition evidence has not been explicitly satisfied, so no action is available.</Text> : presentation === "neutral" ? <Text as="p" tone="subdued">No missing-link action is established by the current analysis.</Text> : null}</BlockStack></section>; })}</WorkSection>}
    {(family === "all" || family === "redirects") && <WorkSection title="Redirects"><Text as="p" tone="subdued">Store Pilot observation determines whether an exact-source redirect is satisfied, missing and actionable, or conflicting and advisory.</Text>{visibleRedirects.map(row => <TechnicalRow key={row.source} title={row.source} detail={row.requiredAction ?? "Review redirect"} details={[`Rule status: ${row.policy.resolutionStatus}`, `Redirect ID: ${row.redirectId ?? "Not available"}`, `Topic relevant: ${row.topicRelevant ?? "Not specified"}`, `Configured target: ${row.configuredTarget ?? "Not configured"}`, `Final target: ${row.finalTarget}`, `Known state: ${row.knownState ?? "Not observed"}`, `Hop count: ${row.hopCount ?? "Unknown"}`]} warning="Matching redirects are satisfied. Missing exact sources may become create-only tasks after approval; conflicting source redirects remain advisory and are never updated automatically." badge="Managed in Store Pilot" ruleIds={row.ruleIds} map={map}/>)}</WorkSection>}
    {(family === "all" || family === "canonical") && <WorkSection title="Canonicalization">{map.work.canonicalization.filter(row => visible(row.priority, "advisory", "review")).map(row => <TechnicalRow key={row.currentUrl} title={row.currentUrl} detail={row.decision ?? "Review canonical"} details={[`Proposed canonical URL: ${row.proposedCanonicalUrl}`, `Priority: ${row.priority ?? "unspecified"}`, `Evidence: ${row.evidence ?? "Not specified"}`, `Publishing state: ${row.publishingState ?? "Not specified"}`]} warning="Package contract permits advisory review only; canonical live execution is prohibited." actionLabel="Advisory only" ruleIds={row.ruleIds} map={map}/>)}</WorkSection>}
    {(family === "all" || family === "indexation") && <WorkSection title="Indexation">{map.work.indexation.filter(row => visible(row.priority, "advisory", "review")).map(row => <TechnicalRow key={row.currentUrl} title={row.currentUrl} detail={row.decision ?? "Review indexation"} details={[`Proposed canonical URL: ${row.proposedCanonicalUrl}`, `Priority: ${row.priority ?? "unspecified"}`, `Evidence: ${row.evidence ?? "Not specified"}`, `Publishing state: ${row.publishingState ?? "Not specified"}`]} warning="Package contract permits advisory review only; indexation live execution is prohibited." actionLabel="Advisory only" ruleIds={row.ruleIds} map={map}/>)}</WorkSection>}
    {globalBlockersVisible({ family, priority, state, blocker }) ? <WorkSection title="Evidence gates and high-stakes review requirements">{[...map.blockers.evidence.map(row => ({...row, kind:"evidence"})), ...map.blockers.reviews.map(row => ({...row, kind:"review"}))].filter(row => blocker === "all" || blocker === row.kind).map(row => <section className={styles.listRow} key={row.ruleIds.join()}><BlockStack gap="200"><Text as="h4" variant="headingSm">{row.name}</Text><Text as="p">{row.text}</Text><PolicyDetails policy={row.policy}/>{row.phaseGate ? <Text as="p" variant="bodySm"><b>Governed advisory action:</b> {row.phaseGate.governedAdvisoryAction} · manual review required · execution prohibited</Text> : null}{row.scheduleAuthorityBoundary ? <Text as="p" variant="bodySm"><b>Schedule authority:</b> proposal only · elapsed time does not authorize action · independent safeguards required</Text> : null}<Provenance ruleIds={row.ruleIds} map={map}/></BlockStack></section>)}</WorkSection> : <Text as="p" tone="subdued">Global evidence gates and high-stakes review requirements have no family or priority association, so they are hidden by the current combined filters.</Text>}
  </BlockStack></div>;
}
function WorkSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><BlockStack gap="200"><Text as="h3" variant="headingMd">{title}</Text><div className={styles.compactList}>{children}</div></BlockStack></section>; }
function PolicyDetails({ policy }: { policy: LinkRule["policy"] }) { const requirements = [...policy.conditions, ...policy.evidenceRequirements, ...policy.reviewRequirements]; return <BlockStack gap="100"><Text as="p"><b>Rule status:</b> {policy.resolutionStatus}</Text>{requirements.map((requirement, index) => <Text as="p" variant="bodySm" key={`${requirement.kind}:${index}`}><b>{requirement.kind.replaceAll("_", " ")}:</b> {requirement.text}</Text>)}</BlockStack>; }
function TechnicalRow({ title, detail, details = [], warning, actionLabel, badge = "Live execution prohibited", ruleIds, map }: { title: string; detail: string; details?: string[]; warning: string; actionLabel?: string; badge?: string; ruleIds: string[]; map: TopicalMapCommandCenter }) { return <section className={styles.listRow}><BlockStack gap="200"><InlineStack align="space-between" wrap><Text as="h4" variant="headingSm">{title}</Text><Badge tone="attention">{badge}</Badge></InlineStack><Text as="p">{detail}</Text>{details.map(value => <Text as="p" key={value}>{value}</Text>)}<Text as="p" tone="caution">{warning}</Text>{actionLabel ? <Button size="slim" disabled>{actionLabel}</Button> : null}<Provenance ruleIds={ruleIds} map={map}/></BlockStack></section>; }
