import { Badge, BlockStack, Button, InlineStack, Select, Text } from "@shopify/polaris";
import { useState } from "react";
import type { MapAwareSeoGap } from "@/lib/seo/analysis";
import type { TopicalMapCommandCenter } from "@/lib/topical-map/command-center";
import { Provenance } from "./MapPagesPanel";
import styles from "../seo-pilot-responsive.module.css";

export function priorityBand(priority?: string) { return /^(p0|p1|critical|highest|high)$/i.test(priority ?? "") ? "high" : /^(p2|medium)$/i.test(priority ?? "") ? "medium" : /^(p3|low)$/i.test(priority ?? "") ? "low" : "unspecified"; }
export function workRowMatchesFilters(row: { priority?: string; state: "candidate" | "blocked"; blocker: "clear" | "evidence" | "review" }, filters: { priority: string; state: string; blocker: string }) { return (filters.priority === "all" || priorityBand(row.priority) === filters.priority) && (filters.state === "all" || row.state === filters.state) && (filters.blocker === "all" || row.blocker === filters.blocker); }
export function globalBlockersVisible(filters: { family: string; priority: string; state: string; blocker: string }) { return filters.family === "all" && filters.priority === "all" && (filters.state === "all" || filters.state === "blocked") && filters.blocker !== "clear"; }

export function MapWorkPanel({ map, gaps, busy, done, onPropose }: { map: TopicalMapCommandCenter; gaps: MapAwareSeoGap[]; busy: Set<string>; done: Set<string>; onPropose: (gap: MapAwareSeoGap) => void }) {
  const [family, setFamily] = useState("all"), [priority, setPriority] = useState("all"), [state, setState] = useState("all"), [blocker, setBlocker] = useState("all");
  const linkGap = (from: string, to: string) => gaps.find(g => g.kind === "link" && g.fromUrl === from && g.toUrl === to);
  const visible = (rowPriority: string | undefined, rowState: "candidate" | "blocked", rowBlocker: "clear" | "evidence" | "review") => workRowMatchesFilters({ priority: rowPriority, state: rowState, blocker: rowBlocker }, { priority, state, blocker });
  return <div className={styles.commandCenter}><BlockStack gap="500">
    <BlockStack gap="100"><Text as="h2" variant="headingLg">Links &amp; technical</Text><Text as="p" tone="subdued">Act on governed links here. Technical rules remain visible with accurate execution boundaries.</Text></BlockStack>
    <div className={styles.filterGrid}><Select label="Filter by rule family" options={[{label:"All work",value:"all"},{label:"Internal links",value:"links"},{label:"Redirects",value:"redirects"},{label:"Canonicalization",value:"canonical"},{label:"Indexation",value:"indexation"}]} value={family} onChange={setFamily}/><Select label="Filter by priority" options={[{label:"All priorities",value:"all"},{label:"High",value:"high"},{label:"Medium",value:"medium"},{label:"Low",value:"low"}]} value={priority} onChange={setPriority}/><Select label="Filter by state" options={[{label:"All states",value:"all"},{label:"Candidate",value:"candidate"},{label:"Blocked",value:"blocked"}]} value={state} onChange={setState}/><Select label="Filter by blocker" options={[{label:"All blocker states",value:"all"},{label:"Clear",value:"clear"},{label:"Evidence",value:"evidence"},{label:"Review",value:"review"}]} value={blocker} onChange={setBlocker}/></div>
    {(family === "all" || family === "links") && <WorkSection title="Required internal links">{map.work.internalLinks.filter(link => visible(link.priority, linkGap(link.fromUrl, link.toUrl) ? "candidate" : "blocked", linkGap(link.fromUrl, link.toUrl) ? "clear" : "evidence")).map(link => { const gap = linkGap(link.fromUrl, link.toUrl); const key = gap?.ruleIds.join("|") ?? link.ruleIds.join("|"); return <section className={styles.listRow} key={`${link.fromUrl}-${link.toUrl}`}><BlockStack gap="200"><Text as="h4" variant="headingSm">{link.fromUrl} → {link.toUrl}</Text><Text as="p">{link.requiredAction ?? "Add required internal link"}</Text><Text as="p" tone="subdued">Priority: {link.priority ?? "unspecified"} · State: {gap ? "candidate" : "blocked"} · Anchor: {link.recommendedAnchor ?? "Use map-approved context"}</Text><InlineStack align="space-between" blockAlign="center" wrap><Provenance ruleIds={link.ruleIds} map={map}/>{done.has(key) ? <Badge tone="success">Proposal created</Badge> : <Button size="slim" variant="primary" disabled={!gap} loading={busy.has(key)} onClick={() => gap && onPropose(gap)}>Create link proposal</Button>}</InlineStack>{!gap && <Text as="p" tone="caution">Evidence blocker: no actionable analysis candidate exists for this rule.</Text>}</BlockStack></section>; })}</WorkSection>}
    {(family === "all" || family === "redirects") && <WorkSection title="Redirects">{map.work.redirects.filter(row => visible(row.priority, "blocked", "review")).map(row => <TechnicalRow key={row.source} title={`${row.source} → ${row.finalTarget}`} detail={row.requiredAction ?? row.knownState ?? "Review redirect"} warning="Redirect proposal persistence is not supported by Content Pilot; route this reviewed rule through a separately governed redirect workflow." actionLabel="Redirect proposal unavailable" ruleIds={row.ruleIds} map={map}/>)}</WorkSection>}
    {(family === "all" || family === "canonical") && <WorkSection title="Canonicalization">{map.work.canonicalization.filter(row => visible(row.priority, "blocked", "review")).map(row => <TechnicalRow key={row.currentUrl} title={`${row.currentUrl} → ${row.proposedCanonicalUrl}`} detail={row.decision ?? row.evidence ?? "Review canonical"} warning="Package contract permits advisory review only; canonical live execution is prohibited." actionLabel="Advisory only" ruleIds={row.ruleIds} map={map}/>)}</WorkSection>}
    {(family === "all" || family === "indexation") && <WorkSection title="Indexation">{map.work.indexation.filter(row => visible(row.priority, "blocked", "review")).map(row => <TechnicalRow key={row.currentUrl} title={row.currentUrl} detail={row.decision ?? row.publishingState ?? "Review indexation"} warning="Package contract permits advisory review only; indexation live execution is prohibited." actionLabel="Advisory only" ruleIds={row.ruleIds} map={map}/>)}</WorkSection>}
    {globalBlockersVisible({ family, priority, state, blocker }) ? <WorkSection title="Evidence and review blockers">{[...map.blockers.evidence.map(row => ({...row, kind:"evidence"})), ...map.blockers.reviews.map(row => ({...row, kind:"review"}))].filter(row => blocker === "all" || blocker === row.kind).map(row => <section className={styles.listRow} key={row.ruleIds.join()}><BlockStack gap="200"><Text as="h4" variant="headingSm">{row.name}</Text><Text as="p">{row.text}</Text><Provenance ruleIds={row.ruleIds} map={map}/></BlockStack></section>)}</WorkSection> : <Text as="p" tone="subdued">Global evidence and review blockers have no family or priority association, so they are hidden by the current combined filters.</Text>}
  </BlockStack></div>;
}
function WorkSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><BlockStack gap="200"><Text as="h3" variant="headingMd">{title}</Text><div className={styles.compactList}>{children}</div></BlockStack></section>; }
function TechnicalRow({ title, detail, warning, actionLabel, ruleIds, map }: { title: string; detail: string; warning: string; actionLabel: string; ruleIds: string[]; map: TopicalMapCommandCenter }) { return <section className={styles.listRow}><BlockStack gap="200"><InlineStack align="space-between" wrap><Text as="h4" variant="headingSm">{title}</Text><Badge tone="attention">Live execution prohibited</Badge></InlineStack><Text as="p">{detail}</Text><Text as="p" tone="caution">{warning}</Text><Button size="slim" disabled>{actionLabel}</Button><Provenance ruleIds={ruleIds} map={map}/></BlockStack></section>; }
