import { createHash } from "node:crypto";
import { REQUIRED_ARTIFACT_IDS, type StrategyArtifactId, type StrategyManifest } from "./types";
export type StrategyPackageErrorCode = "INVALID_MANIFEST" | "UNSUPPORTED_SCHEMA" | "INCOMPATIBLE_RUNTIME" | "SITE_HOST_MISMATCH" | "MISSING_ARTIFACT" | "DUPLICATE_ARTIFACT" | "UNKNOWN_ARTIFACT" | "INVALID_SHA256" | "VERSION_MISMATCH" | "PACKAGE_HASH_MISMATCH" | "UNSAFE_PATH" | "SYMLINK_ESCAPE" | "HASH_MISMATCH" | "MISSING_FILE";
export class StrategyPackageError extends Error { constructor(public readonly code: StrategyPackageErrorCode, message: string) { super(message); this.name = "StrategyPackageError"; } }
const hash = (value: Buffer | string) => createHash("sha256").update(value).digest("hex");
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const sha = /^[a-f0-9]{64}$/; const date = /^\d{4}-\d{2}-\d{2}$/;
export function canonicalJson(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; if (isRecord(value)) return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(",")}}`; return JSON.stringify(value); }
export function derivePackageSha256(manifest: Omit<StrategyManifest, "packageSha256">): string { return hash(`${canonicalJson(manifest)}\n${manifest.artifacts.map((artifact) => artifact.sha256).join("\n")}`); }
export function parseManifest(value: unknown): StrategyManifest {
  if (!isRecord(value) || !Array.isArray(value.artifacts) || !isRecord(value.compatibility) || !isRecord(value.provenance) || !isRecord(value.approval)) throw new StrategyPackageError("INVALID_MANIFEST", "Manifest is malformed.");
  if (value.schemaVersion !== "1.0.0") throw new StrategyPackageError("UNSUPPORTED_SCHEMA", "Unsupported manifest schema.");
  if (value.compatibility.runtimeSchema !== ">=1.0.0 <2.0.0") throw new StrategyPackageError("INCOMPATIBLE_RUNTIME", "Unsupported runtime compatibility.");
  if (value.compatibility.siteHost !== "agrikoph.com") throw new StrategyPackageError("SITE_HOST_MISMATCH", "Unsupported site host.");
  for (const key of ["packageId", "strategyVersion", "evidenceDate", "createdAt", "packageSha256"]) if (typeof value[key] !== "string") throw new StrategyPackageError("INVALID_MANIFEST", `Invalid ${key}.`);
  if (!date.test(value.strategyVersion as string) || !date.test(value.evidenceDate as string) || value.packageId !== `agriko-topical-map-${value.strategyVersion}` || Number.isNaN(Date.parse(value.createdAt as string))) throw new StrategyPackageError("INVALID_MANIFEST", "Invalid version or date.");
  if (!sha.test(value.packageSha256 as string)) throw new StrategyPackageError("INVALID_SHA256", "Invalid package hash.");
  const seen = new Set<string>(); const artifacts = value.artifacts.map((entry): StrategyManifest["artifacts"][number] => { if (!isRecord(entry) || typeof entry.id !== "string" || typeof entry.path !== "string" || typeof entry.mediaType !== "string" || typeof entry.sha256 !== "string" || entry.required !== true) throw new StrategyPackageError("INVALID_MANIFEST", "Invalid artifact."); if (/\0/.test(entry.path) || /^(?:\/|[A-Za-z]:[\\/])/.test(entry.path) || entry.path.split(/[\\/]/).includes("..")) throw new StrategyPackageError("UNSAFE_PATH", "Unsafe artifact path."); if (!REQUIRED_ARTIFACT_IDS.includes(entry.id as StrategyArtifactId)) throw new StrategyPackageError("UNKNOWN_ARTIFACT", "Unknown artifact."); if (seen.has(entry.id)) throw new StrategyPackageError("DUPLICATE_ARTIFACT", "Duplicate artifact."); seen.add(entry.id); if (!sha.test(entry.sha256)) throw new StrategyPackageError("INVALID_SHA256", "Invalid artifact hash."); const expected = entry.id === "map" ? `agriko-topical-map-${value.strategyVersion}.md` : entry.id === "evidence" ? `agriko-topical-map-evidence-${value.strategyVersion}.md` : `agriko-topical-map-${entry.id}-${value.strategyVersion}.csv`; const mediaType = entry.id === "map" || entry.id === "evidence" ? "text/markdown" : "text/csv"; if (entry.path !== expected) throw new StrategyPackageError("VERSION_MISMATCH", "Artifact filename/version mismatch."); if (entry.mediaType !== mediaType) throw new StrategyPackageError("INVALID_MANIFEST", "Artifact media type is invalid."); return { id: entry.id as StrategyArtifactId, path: entry.path, mediaType, sha256: entry.sha256, required: true }; });
  for (const id of REQUIRED_ARTIFACT_IDS) if (!seen.has(id)) throw new StrategyPackageError("MISSING_ARTIFACT", "Missing required artifact.");
  const manifest = { schemaVersion: "1.0.0" as const, packageId: value.packageId as string, strategyVersion: value.strategyVersion as string, evidenceDate: value.evidenceDate as string, createdAt: value.createdAt as string, provenance: value.provenance, compatibility: value.compatibility as StrategyManifest["compatibility"], artifacts, packageSha256: value.packageSha256 as string, approval: value.approval };
  const withoutHash = Object.fromEntries(Object.entries(manifest).filter(([key]) => key !== "packageSha256")) as Omit<StrategyManifest, "packageSha256">; if (derivePackageSha256(withoutHash) !== manifest.packageSha256) throw new StrategyPackageError("PACKAGE_HASH_MISMATCH", "Package hash mismatch."); return manifest;
}
